/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, { Component } from 'react';
import { Alert, StyleSheet, Text, View, Button } from 'react-native';

// ############################# HLF Services #####################################
import HlfSdk from 'react-native-hlf-wrapper';
let connection_profile = require("./connection_profile.json");

const test = async () =>  {
    let message = await HlfSdk.hello();
    Alert.alert("☆NATIVE PROMISE MESSAGE (test)☆", message);
}

const connectionProfileSetup = async () =>  {
    await HlfSdk.connectionProfileSetup(connection_profile);
    Alert.alert("☆NATIVE PROMISE MESSAGE (cpp setup)☆", "...see console");
}

const enrollUser = async (user, secret) =>  {
    let message = await HlfSdk.enrollUser(user, secret);
    Alert.alert("☆NATIVE PROMISE MESSAGE (enroll)☆", message);
}

const lsRNFS = async () => {
    await HlfSdk.lsRNFS();
    Alert.alert("☆NATIVE PROMISE MESSAGE (ls)☆", "...see console");
}

// #############################################################################

export default class App extends Component<{}> {
  render() {
    return (
      <View style={styles.container}>
        <Text style={styles.welcome}>☆HlfWrapper example☆</Text>
        <Button  title={"Native Test"} onPress={test} />
        <View style={{flex:0.01}} />
        <Button  title={"Setup: Connection Profile"} onPress={connectionProfileSetup} />
        <View style={{flex:0.01}} />
        <Button  title={"Enroll User"} onPress={() => enrollUser("user19", "userpw")} />
        <View style={{flex:0.01}} />
        <Button  title={"ls RNFS"} onPress={lsRNFS} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  },
  welcome: {
    fontSize: 20,
    textAlign: 'center',
    margin: 10,
  },
  instructions: {
    textAlign: 'center',
    color: '#333333',
    marginBottom: 5,
  },
});
